version: '3'

networks:
  default:

services:
  # server clickhouse
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:20.6.8
    build:
      context: ./clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/clickhouse_database/:/var/lib/clickhouse # данные clickhouse
      - ./clickhouse/logs_api_integration/:/usr/src # код проекта logs_api_integration
    env_file:
      - "./config.env"
	ports:
      - 8123:8123
  # clickhouse gui
  tabix:
    container_name: tabix
    build:
      context: ./tabix
	env_file:
      - "./env/tabix.env"
    ports:
      - 8080:80