version: '3'

networks:
  default:

services:
  # Memcache сервер для API
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:20.6.8
    build:
      context: ./clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/clickhouse_database/:/var/lib/clickhouse # данные clickhouse
      - ./clickhouse/logs_api_integration/:/usr/src # код проекта logs_api_integration